version: '3.9'

services:
  react-app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - '../:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '5173:5173'
    environment:
      - NODE_ENV=development